# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Reference: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
# NOTE: dependabot only takes care of updating non-npm deps
# npm dependencies are updated through the "yarn-upgrade" github workflow.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "auto-approve"
    open-pull-requests-limit: 5
